apiVersion: v1
data:
  environment.json: |
    {
      "KEYCLOAK_URL": "https://keycloak.pulse8.synpulse8.com",
      "KEYCLOAK_CLIENT_ID": "angular-client-test",
      "KEYCLOAK_REALM": "pulse8_wealth_cockpit"
    }
kind: ConfigMap
metadata:
  name: pulse8-yourname-frontend-config
  namespace: default
