# Changes here will be overwritten by Copier
_commit: v0.0.17-4-gb3f87bc
_src_path: .
auth: true
build_for_arm: false
project_desc: Template build full
project_id: pulse8-yourname-frontend
project_name: Pulse8 YourName Frontend
store: true
store_example: true
