/*
    This is example data just for testing and the examples, please delete this file if not needed
 */
import { MockData } from './shared/models/mock-data.model'

export const data: MockData[] = [
  {
    id: '64ed7fe0ea51679a6663be7e',
    index: 0,
    age: 27,
    eyeColor: 'blue',
    name: 'Cobb Conrad',
    gender: 'male',
    email: 'cobbconrad@moltonic.com',
    address: '546 Kings Hwy, Boykin, Kansas,9623',
    greeting: '',
    favoriteFruit: 'apple',
  },
  {
    id: '64ed7fe0b4fc7a574a3b10a3',
    index: 1,
    age: 25,
    eyeColor: 'green',
    name: 'Desiree Faulkner',
    gender: 'female',
    email: 'desireefaulkner@moltonic.com',
    address: '819 Beadel Street, Martell, New Hampshire,6804',
    greeting: '',
    favoriteFruit: 'banana',
  },
  {
    id: '64ed7fe01be6e91345ef2881',
    index: 2,
    age: 24,
    eyeColor: 'blue',
    name: 'Sheppard Reese',
    gender: 'male',
    email: 'sheppardreese@moltonic.com',
    address: '929 Tech Place, Foxworth, South Carolina,9867',
    greeting: '',
    favoriteFruit: 'apple',
  },
  {
    id: '64ed7fe09cae49c5d4644313',
    index: 3,
    age: 27,
    eyeColor: 'green',
    name: 'Hernandez Bryant',
    gender: 'male',
    email: 'hernandezbryant@moltonic.com',
    address: '401 National Drive, Suitland, Michigan,3023',
    greeting: '',
    favoriteFruit: 'strawberry',
  },
  {
    id: '64ed7fe0ffbf5363bcd8101f',
    index: 4,
    age: 39,
    eyeColor: 'brown',
    name: 'Deirdre Lindsey',
    gender: 'female',
    email: 'deirdrelindsey@moltonic.com',
    address: '795 Falmouth Street, Basye, Florida,6145',
    greeting: '',
    favoriteFruit: 'strawberry',
  },
  {
    id: '64ed7fe0e885de81b17ad5ba',
    index: 5,
    age: 39,
    eyeColor: 'brown',
    name: 'Cortez Key',
    gender: 'male',
    email: 'cortezkey@moltonic.com',
    address: '793 Columbia Street, Wikieup, West Virginia,9207',
    greeting: '',
    favoriteFruit: 'apple',
  },
  {
    id: '64ed7fe00efa63593c749eaf',
    index: 6,
    age: 33,
    eyeColor: 'green',
    name: 'Bridgett Clements',
    gender: 'female',
    email: 'bridgettclements@moltonic.com',
    address: '492 Catherine Street, Winchester, Vermont,6832',
    greeting: '',
    favoriteFruit: 'strawberry',
  },
]
