# Changes here will be overwritten by Copier
_commit: v0.0.17-47-g28f0543
_src_path: .
add_sonar: true
auth: true
build_for_arm: false
project_desc: Template build full
project_id: pulse8-yourname-frontend
project_name: Pulse8 YourName Frontend
sonar_project_key_suffix: pulse8-core-frontend-template
store: true
store_example: true
