name: Pulse8 Core Angular Template CI

on:
  push:
    branches:
      - feature/build-piplines-sonar
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies using pnpm
        run: pnpm install

      - name: Call SPA build and push container workflow
        uses: synpulse-group/s8-actions/custom-build-push-container@feature/angular-template
        with:
          docker-file-path: ./builds/min/Dockerfile
          docker-build-context-location: ./builds/min
          nginx-conf-path: './builds/min/src/assets/configs/nginx.conf'
          jfrog-user: ${{ secrets.JFROG_USER }} # no need to change - available in all workflows in the organisation
          jfrog-password: ${{ secrets.JFROG_TOKEN }} # no need to change - available in all workflows in the organisation

      # Cache SonarCloud packages
      - name: "Cache SonarCloud packages"
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Analyze with SonarCloud
      - name: "Analyze with SonarCloud"
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
